name: simulator
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  vm_service: ^14.0.0
  window_manager: ^0.3.8

dev_dependencies:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/skins/pixel_2/
    - assets/skins/pixel_2_xl/
    - assets/skins/pixel_3/
    - assets/skins/pixel_3_xl/
    - assets/skins/pixel_3a/
    - assets/skins/pixel_3a_xl/
    - assets/skins/pixel_4/
    - assets/skins/pixel_4_xl/
    - assets/skins/pixel_2/
    - assets/skins/pixel_4a/
    - assets/skins/pixel_5/
    - assets/skins/pixel_6/
    - assets/skins/pixel_6_pro/
    - assets/skins/pixel_6a/
    - assets/skins/pixel_7/
    - assets/skins/pixel_7_pro/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
